name: Udagram P03 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag udagram-frontend:local sonnt247/udagram-frontend:v1
    - run: docker tag reverseproxy sonnt247/reverseproxy:v1
    - run: docker tag udagram-api-user sonnt247/udagram-api-user:v1
    - run: docker tag udagram-api-feed sonnt247/udagram-api-feed:v1
    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
    - run: docker push sonnt247/udagram-frontend:v2
    - run: docker push sonnt247/reverseproxy:v1
    - run: docker push sonnt247/udagram-api-user:v1
    - run: docker push sonnt247/udagram-api-feed:v1
